language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
branches:
  only:
  - master
  - develop
services:
- docker
install:
- docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=cp --name briefy-cp-test mysql:5.7
- pip install -r requirements.txt
- buildout -c dev.cfg
script:
- bin/test
after_success:
- git fetch --unshallow
notifications:
  slack: briefy:qxjOPwcrGEtVx3aCQBr812t9
